package org.kit.filter.query;

import java.util.function.Predicate;

/**
 * Node class generated by JJTree/java (by NodeFiles.java with java/SingleNode.template)
 * that extends the generated base node class Node.
 */
class And extends Node implements PredicateMaker {

	public And(final FilterQuery parser, final int id) {
		super(parser, id);
	}

	@Override
	public <T> Predicate<T> criterion() {
		return t -> {
			for (Node n : jjtGetChildren())
				if (n instanceof PredicateMaker p)
					if (!p.criterion().test(t))
						return false;
			return true;
		};
	}
}
