package org.kit.filter.query;

import java.util.function.Predicate;

/**
 * Node class generated by JJTree/java (by NodeFiles.java with java/SingleNode.template)
 * that extends the generated base node class Node.
 */
class Between extends Compare {

	private Object lower;

	private Object upper;

	public Between(final FilterQuery p, final int id) {
		super(p, id);
	}

	@Override
	public void jjtClose() {
		super.jjtClose();
		if (3 > jjtGetNumChildren())
			throw new IllegalStateException("Operation " + FilterQueryTreeConstants.jjtNodeName[id] + " has less arguments than expected");
		lower = parser.coarse(fieldName, ((Literal) jjtGetChild(1)).value());
		upper = parser.coarse(fieldName, ((Literal) jjtGetChild(2)).value());
	}

	@Override
	public <T> Predicate<T> criterion() {
		return t -> parser.resolver()
				.andThen(v -> 0 <= compare(v, lower) && 0 > compare(v, upper))
				.apply(t, fieldName);
	}
}
