package org.kit.filter.query;

import java.util.stream.Stream;

/**
 * Node class generated by JJTree/java (by NodeFiles.java with java/SingleNode.template)
 * that extends the generated base node class Node.
 */
abstract class Compare extends Node implements PredicateMaker {

	protected String fieldName;

	public Compare(final FilterQuery parser, final int id) {
		super(parser, id);
	}

	@Override
	public void jjtClose() {
		super.jjtClose();
		if (2 > jjtGetNumChildren())
			throw new IllegalStateException("Operation " + FilterQueryTreeConstants.jjtNodeName[id] + " has less arguments than expected");
		fieldName = Stream.of(jjtGetChildren())
				.filter(n -> n instanceof Field)
				.map(n -> ((Field) n).name())
				.findFirst()
				.orElseThrow(() -> new IllegalStateException("Unable to identify the data type. No field identifier"));
	}

	@SuppressWarnings({"rawtypes", "unchecked"})
	static int compare(Object left, Object right) {
		if (left instanceof Comparable c1 && right instanceof Comparable c2)
			return c1.compareTo(c2);
		return left == null ? right == null ? 0 : -1 : 1;
	}
}
