package org.kit.filter.query;

import java.util.function.Predicate;

/**
 * Node class generated by JJTree/java (by NodeFiles.java with java/SingleNode.template)
 * that extends the generated base node class Node.
 */
class Contains extends Compare {

	private Object left;

	private Object right;

	public Contains(final FilterQuery p, final int id) {
		super(p, id);
	}

	@Override
	public void jjtClose() {
		super.jjtClose();
		if (jjtGetChild(0) instanceof Literal l)
			left = parser.coarse(fieldName, l.value());
		if (jjtGetChild(1) instanceof Literal l)
			right = parser.coarse(fieldName, l.value());
	}

	@Override
	public <T> Predicate<T> criterion() {
		return t -> {
			if (null == left)
				return parser.resolver()
						.andThen(v -> contains(v, right))
						.apply(t, fieldName);
			return parser.resolver()
					.andThen(v -> contains(left, v))
					.apply(t, fieldName);
		};
	}
	static boolean contains(Object left, Object right) {
		if (left instanceof String s && right instanceof CharSequence p)
			return s.contains(p);
		return false;
	}
}
