package org.kit.filter.query;

import java.util.Objects;
import java.util.function.Predicate;

/**
 * Node class generated by JJTree/java (by NodeFiles.java with java/SingleNode.template)
 * that extends the generated base node class Node.
 */
class Equal extends Compare {

	private Object left;

	private Object right;

	public Equal(final FilterQuery p, final int id) {
		super(p, id);
	}

	@Override
	public void jjtClose() {
		super.jjtClose();
		if (jjtGetChild(0) instanceof Literal l)
			left = parser.coarse(fieldName, l.value());
		if (jjtGetChild(1) instanceof Literal l)
			right = parser.coarse(fieldName, l.value());
	}

	@Override
	public <T> Predicate<T> criterion() {
		if (null != left)
			return t -> parser.<T, Object>resolver()
					.andThen(v -> Objects.equals(v, left))
					.apply(t, fieldName);
		return t -> parser.<T, Object>resolver()
				.andThen(v -> Objects.equals(v, right))
				.apply(t, fieldName);
	}
}
