package org.kit.filter.query;

import java.util.function.Predicate;

/**
 * Node class generated by JJTree/java (by NodeFiles.java with java/SingleNode.template)
 * that extends the generated base node class Node.
 */
class Expression extends Node implements PredicateMaker {

	public Expression(final FilterQuery p, final int id) {
		super(p, id);
	}

	@Override
	public void jjtClose() {
		if (1 != jjtGetNumChildren())
			throw new IllegalStateException("Impossible syntactic nuisance");
		if (!(jjtGetChild(0) instanceof PredicateMaker))
			throw new IllegalStateException("Impossible syntactic nuisance");
	}

	@Override
	public <T> Predicate<T> criterion() {
		return ((PredicateMaker) jjtGetChild(0)).criterion();
	}
}
