package org.kit.filter.query;

/**
 * Node class generated by JJTree/java (by NodeFiles.java with java/SingleNode.template)
 * that extends the generated base node class Node.
 */
class Field extends Node {

	private String name;

	public Field(final FilterQuery parser, final int id) {
		super(parser, id);
	}

	@Override
	public void jjtClose() {
		name = parser.getToken(0).image;
	}

	public String name() {
		return name;
	}

	public String toString() {
		return "Field '" + name + '\'';
	}
}
