package org.kit.filter.query;

import java.util.function.Predicate;

/**
 * Node class generated by JJTree/java (by NodeFiles.java with java/SingleNode.template)
 * that extends the generated base node class Node.
 */
class Greater extends Compare {

	private Object left;

	private Object right;

	public Greater(final FilterQuery p, final int id) {
		super(p, id);
	}

	@Override
	public void jjtClose() {
		super.jjtClose();
		if (jjtGetChild(0) instanceof Literal l)
			left = parser.coarse(fieldName, l.value());
		if (jjtGetChild(1) instanceof Literal l)
			right = parser.coarse(fieldName, l.value());
	}

	@Override
	public <T> Predicate<T> criterion() {
		return t -> {
			if (null == left)
				return parser.resolver()
						.andThen(v -> 0 < compare(v, right))
						.apply(t, fieldName);
			return parser.resolver()
					.andThen(v -> 0 > compare(v, left))
					.apply(t, fieldName);
		};
	}
}
