package org.kit.filter.query;

import java.util.HashSet;
import java.util.Set;
import java.util.function.Predicate;

/**
 * Node class generated by JJTree/java (by NodeFiles.java with java/SingleNode.template)
 * that extends the generated base node class Node.
 */
class In extends Compare {

	private Set<Object> list;

	public In(final FilterQuery p, final int id) {
		super(p, id);
	}

	@Override
	public void jjtClose() {
		super.jjtClose();
		list = new HashSet<>(jjtGetNumChildren(), 1F);
		for (int i = 1; i < jjtGetNumChildren(); i++)
			if (jjtGetChild(i) instanceof Literal l)
				list.add(parser.coarse(fieldName, l.value()));
	}

	@Override
	public <T> Predicate<T> criterion() {
		return t -> parser.resolver()
				.andThen(v -> list.contains(v))
				.apply(t, fieldName);
	}

}
