package org.kit.filter.query;

/**
 * Node class generated by JJTree/java (by NodeFiles.java with java/SingleNode.template)
 * that extends the generated base node class Node.
 */
class Literal extends Node {

	private String value;

	public Literal(final FilterQuery parser, final int id) {
		super(parser, id);
	}

	public String value() {
		return value;
	}

	@Override
	public void jjtClose() {
		Token token = parser.getToken(0);
		value = FilterQueryConstants.STRING_LITERAL == token.kind ? unquote(token.image) : token.image;
	}

	public String toString() {
		return '"' + value + '"';
	}


	@SuppressWarnings("StatementWithEmptyBody")
	static String unquote(String value) {
		if (null != value) {
			int a = 0, b = value.length() - 1;
			for (; a < b && isQuote(value.charAt(a)) && isQuote(value.charAt(b)); a++, b--) {/* intentional empty */}
			return value.substring(a, b + 1);
		}
		return null;
	}

	static boolean isQuote(char c) {
		return switch (c) {
			case '\'', '"' -> true;
			default -> false;
		};
	}

}
